language: c
compiler:
- clang
sudo: false
cache: ccache

jobs:
  include:
    - name: sanity
      python: 3.4 # oldest 3.x available on Travis
      apt:
        packages:
        - doxygen
        - graphviz
      install:
        - pip install pylint==2.4.4
      script:
        - tests/scripts/all.sh 'check_*'

    - name: default configuration
      script:
        - cmake -D CMAKE_BUILD_TYPE:String="Check" .
        - make
        - make test
        - programs/test/selftest
        - OSSL_NO_DTLS=1 tests/compat.sh
        - tests/ssl-opt.sh -e '\(DTLS\|SCSV\).*openssl'

    - name: enumerated configurations
      script:
        - tests/scripts/test-ref-configs.pl
        - tests/scripts/curves.pl
        - tests/scripts/key-exchanges.pl

after_failure:
- tests/scripts/travis-log-failure.sh

env:
  global:
    - SEED=1
    - secure: "FrI5d2s+ckckC17T66c8jm2jV6i2DkBPU5nyWzwbedjmEBeocREfQLd/x8yKpPzLDz7ghOvr+/GQvsPPn0dVkGlNzm3Q+hGHc/ujnASuUtGrcuMM+0ALnJ3k4rFr9xEvjJeWb4SmhJO5UCAZYvTItW4k7+bj9L+R6lt3TzQbXzg="

addons:
  coverity_scan:
    project:
      name: "ARMmbed/mbedtls"
    notification_email: support-mbedtls@arm.com
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_scan
