#define MBEDTLS_DEPRECATED_REMOVED

#undef MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
/* Some code specific to FFDH in TLS 1.2 is gated by MBEDTLS_DHM_C
 * rather than MBEDTLS_KEY_EXCHANGE_DHE_xxx_ENABLED */
#undef MBEDTLS_DHM_C

#undef MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
