#!/usr/bin/env python
"""Test the configuration checks generated by generate_config_checks.py.
"""

## Copyright The Mbed TLS Contributors
## SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import unittest

import scripts_path # pylint: disable=unused-import
from mbedtls_framework import test_config_checks_generator


class MbedtlsTestConfigChecks(test_config_checks_generator.TestConfigChecks):
    """Mbed TLS unit tests for checks generated by config_checks_generator."""

    #pylint: disable=invalid-name # uppercase letters make sense here

    PROJECT_CONFIG_C = 'library/mbedtls_config.c'
    PROJECT_SPECIFIC_INCLUDE_DIRECTORIES = [
        'tf-psa-crypto/include',
        'tf-psa-crypto/drivers/builtin/include',
    ]

    def test_crypto_define_MBEDTLS_USE_PSA_CRYPTO(self) -> None:
        self.bad_case('#define MBEDTLS_USE_PSA_CRYPTO',
                      error=('MBEDTLS_USE_PSA_CRYPTO is no longer supported' +
                             '.*always on'))

    def test_crypto_undef_MBEDTLS_USE_PSA_CRYPTO(self) -> None:
        self.bad_case('#undef MBEDTLS_USE_PSA_CRYPTO',
                      error=('MBEDTLS_USE_PSA_CRYPTO is no longer supported' +
                             '.*always on'))

    def test_crypto_exempt_define_MBEDTLS_USE_PSA_CRYPTO(self) -> None:
        self.good_case('#define MBEDTLS_USE_PSA_CRYPTO',
                       extra_options=['-DMBEDTLS_CONFIG_CHECK_ALLOW_REMOVED_OPTIONS'])

    def test_crypto_exempt_undef_MBEDTLS_USE_PSA_CRYPTO(self) -> None:
        self.good_case('#undef MBEDTLS_USE_PSA_CRYPTO',
                       extra_options=['-DMBEDTLS_CONFIG_CHECK_ALLOW_REMOVED_OPTIONS'])


if __name__ == '__main__':
    unittest.main()
