#!/usr/bin/env python
"""Test the configuration checks generated by generate_config_checks.py.
"""

## Copyright The Mbed TLS Contributors
## SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import unittest

import scripts_path # pylint: disable=unused-import
from mbedtls_framework import unittest_config_checks


class MbedtlsTestConfigChecks(unittest_config_checks.TestConfigChecks):
    """Mbed TLS unit tests for checks generated by config_checks_generator."""

    #pylint: disable=invalid-name # uppercase letters make sense here

    PROJECT_CONFIG_C = 'library/mbedtls_config.c'
    PROJECT_SPECIFIC_INCLUDE_DIRECTORIES = [
        'tf-psa-crypto/include',
        'tf-psa-crypto/drivers/builtin/include',
    ]

    def test_mbedtls_define_MBEDTLS_KEY_EXCHANGE_RSA_ENABLED(self) -> None:
        self.bad_case('#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED',
                      error=('MBEDTLS_KEY_EXCHANGE_RSA_ENABLED was removed'))

    def test_mbedtls_exempt_define_MBEDTLS_KEY_EXCHANGE_RSA_ENABLED(self) -> None:
        self.good_case('#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED',
                       extra_options=['-DMBEDTLS_CONFIG_CHECK_BYPASS'])


if __name__ == '__main__':
    unittest.main()
